metadata:
  author: SilverLive Quantum
  projectname: QuantumPhotoEditor
  version: development
build:
  theme:
    name: yndroid_silverlive_theme
  source: docs
publish:
  ghpages:
    url: silverlive.quantum

